name: Sunucu Başlat

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  serve:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
    - name: Kodu indir
      uses: actions/checkout@v3
    
    - name: Node.js kur
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Bağımlılıkları yükle
      working-directory: ./project
      run: npm install
    
    - name: Sunucuyu başlat
      working-directory: ./project
      run: npm start
